package org.infinitybots.bot.gui;

import org.infinitybots.bot.smithing.Smith;
import org.powerbot.concurrent.strategy.Strategy;

/**
 * 
 * @author Brad
 * 
 * Generated by netbeans
 *
 */
public class Gui extends javax.swing.JFrame {

	final Smith setup = new Smith();
	
	private boolean done = false;
	
	private String[] items = { "dagger", "hatchet", "mace", "helm", "sword", "scimitar", "longsword", "full helm", "knife", "claws", "warhammer",
			"battleaxe", "chainbody", "kiteshield", "2h sword", "plateskirt", "platelegs", "platebody"};
	
   public Gui() {
       initComponents();
   }
   @SuppressWarnings("rawtypes")
   private void initComponents() {
	   TabedPane = new javax.swing.JTabbedPane();
       Forge = new javax.swing.JPanel();
       ItemComboBox = new javax.swing.JComboBox();
       ForgeTypeComboBox = new javax.swing.JComboBox();
       jLabel1 = new javax.swing.JLabel();
       ForgeStart = new javax.swing.JButton();
       ForgeAreaComboBox = new javax.swing.JComboBox();
       Smelt = new javax.swing.JPanel();
       SmeltTypeComboBox = new javax.swing.JComboBox();
       jLabel2 = new javax.swing.JLabel();
       SmeltStart = new javax.swing.JButton();
       SmeltArea = new javax.swing.JComboBox();

       //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
       setTitle("Infinity Mining and Smithing");
       setResizable(false);
       
       ItemComboBox.setModel(new javax.swing.DefaultComboBoxModel(items));

       ForgeTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bronze", "Iron", "Steel", "Mithril", "Adamant", "Rune" }));

       jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
       jLabel1.setText("Choose Your Item");

       ForgeStart.setText("Start");
       ForgeStart.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               ForgeStartActionPerformed(evt);
           }
       });

       ForgeAreaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Varrock West Bank" }));

       javax.swing.GroupLayout ForgeLayout = new javax.swing.GroupLayout(Forge);
       Forge.setLayout(ForgeLayout);
       ForgeLayout.setHorizontalGroup(
           ForgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ForgeLayout.createSequentialGroup()
               .addContainerGap(21, Short.MAX_VALUE)
               .addComponent(jLabel1)
               .addGap(25, 25, 25))
           .addGroup(ForgeLayout.createSequentialGroup()
               .addGap(109, 109, 109)
               .addComponent(ForgeStart)
               .addContainerGap())
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ForgeLayout.createSequentialGroup()
               .addComponent(ForgeTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(32, 32, 32)
               .addComponent(ForgeAreaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(ItemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
       );
       ForgeLayout.setVerticalGroup(
           ForgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ForgeLayout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(18, 18, 18)
               .addGroup(ForgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(ItemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(ForgeTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(ForgeAreaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
               .addComponent(ForgeStart)
               .addContainerGap())
       );

       TabedPane.addTab("Forging", Forge);

       SmeltTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bronze", "Iron", "Steel", "Gold", "Mithril", "Adamant", "Rune", "Cannon balls" }));

       jLabel2.setFont(new java.awt.Font("Stencil", 1, 24));
       jLabel2.setText("Choose your Options");

       SmeltStart.setText("Start");
       SmeltStart.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               SmeltStartActionPerformed(evt);
           }
       });

       SmeltArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Al Kharid", "Edgeville" }));

       javax.swing.GroupLayout SmeltLayout = new javax.swing.GroupLayout(Smelt);
       Smelt.setLayout(SmeltLayout);
       SmeltLayout.setHorizontalGroup(
           SmeltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(SmeltLayout.createSequentialGroup()
               .addContainerGap()
               .addComponent(SmeltTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(SmeltArea, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(20, 20, 20))
           .addGroup(SmeltLayout.createSequentialGroup()
               .addGap(111, 111, 111)
               .addComponent(SmeltStart)
               .addContainerGap())
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SmeltLayout.createSequentialGroup()
               .addGap(0, 2, Short.MAX_VALUE)
               .addComponent(jLabel2))
       );
       SmeltLayout.setVerticalGroup(
           SmeltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SmeltLayout.createSequentialGroup()
               .addGap(26, 26, 26)
               .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(26, 26, 26)
               .addGroup(SmeltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(SmeltTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(SmeltArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(18, 18, 18)
               .addComponent(SmeltStart)
               .addContainerGap(22, Short.MAX_VALUE))
       );

       TabedPane.addTab("Smelting", Smelt);

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(TabedPane)
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(TabedPane)
       );

       pack();
   }

   private void SmeltStartActionPerformed(java.awt.event.ActionEvent evt) {
	   final String location = (String)SmeltArea.getSelectedItem();
	   final String type = (String) SmeltTypeComboBox.getSelectedItem();
	   setup.setup(location, type);
	   done = true;
	   setVisible(false);
   }
   
   private void ForgeStartActionPerformed(java.awt.event.ActionEvent evt) {
	   final String item = (String) (ForgeTypeComboBox.getSelectedItem()+" "+ItemComboBox.getSelectedItem());
	   setup.setup(item);
	   done = true;
	   setVisible(false);
   }
   public Strategy[] getStrategies(){
	   return setup.getStrategies();
   }
   public boolean isDone(){
	   return done;
   }
   
   private javax.swing.JPanel Forge;
   private javax.swing.JComboBox ForgeAreaComboBox;
   private javax.swing.JButton ForgeStart;
   private javax.swing.JComboBox ForgeTypeComboBox;
   private javax.swing.JComboBox ItemComboBox;
   private javax.swing.JPanel Smelt;
   private javax.swing.JComboBox SmeltArea;
   private javax.swing.JButton SmeltStart;
   private javax.swing.JComboBox SmeltTypeComboBox;
   private javax.swing.JTabbedPane TabedPane;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
}

